### ISSUE TITLE
Python error after installing via `brew`

### ISSUE THREAD

**Issue by Empty2k12** [JakeWharton/pidcat#149]
```
Traceback (most recent call last):
  File "/usr/local/bin/pidcat", line 199, in <module>
    adb = subprocess.Popen(adb_command, stdin=PIPE, stdout=PIPE)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by Zhenyu-Liu** [comment]
I got the same issue, did you found solution for this?

**Comment by jjm901** [comment]
I had this exact same issue. I fixed it by installing adb via brew as well:

brew cask install android-platform-tools
