### ISSUE TITLE
pidcat doesn't produce any output

### ISSUE THREAD

**Issue by delor** [JakeWharton/pidcat#20]
system: Arch Linux 3.9.6-1 x86_64
python version: 2.7.5 and 3.3.2
pidcat version: 571826e8c03b18402025c6d8bd8bad1d367401a8

Pidcat doesn't produce any output. Jeff Sharkey's version works fine.

**Comment by mhubig** [comment]
See #76 for a possible solution!

**Comment by castrojr913** [comment]
Hello jake, the same issue happens me. I'm testing with Android 5.1 and a Nexus 5 .. without logs :(

**Comment by JakeWharton** [comment]
@castrojr913 that is unrelated. Android 5.x has been fixed on `master`.

**Comment by schwiz** [comment]
Jake, did you ever get around to sending that fix up to homebrew? https://github.com/JakeWharton/pidcat/issues/75

**Comment by JakeWharton** [comment]
No

**Comment by lduparc** [comment]
Can you push the fix to homebrew please ?

**Comment by mhubig** [comment]
You can install from master with `brew install pidcat --HEAD` ...

**Comment by davcamer** [comment]
Make sure the device is visible on `adb devices`. :open_mouth:

**Comment by rynkowsg** [comment]
I have the same.

System: 4.0.3-1 x86_64
Python: 2.7.9 and 3.4.3
Pidcat: 660a819

By adding two lines:
```
@@ -242,6 +242,7 @@ ps_pid = subprocess.Popen(ps_command, stdin=PIPE, stdout=PIPE, stderr=PIPE)
 while ps_pid.poll() is None:
   try:
     line = ps_pid.stdout.readline().decode('utf-8', 'replace').strip()
+    print(repr(line))
   except KeyboardInterrupt:
     break
   if len(line) == 0:
@@ -258,6 +259,7 @@ while ps_pid.poll() is None:
 while adb.poll() is None:
   try:
     line = adb.stdout.readline().decode('utf-8', 'replace').strip()
+    print(repr(line))
   except KeyboardInterrupt:
     break
   if len(line) == 0:
```
I got:
```
$ ./pidcat.py -c; ./pidcat.py 
'USER     PID   PPID  VSIZE  RSS     WCHAN    PC        NAME'
'root      1     0     13224  580   c02115b6 0806c200 S /init'
'root      2     0     0      0     c0156f54 00000000 S kthreadd'
'--------- beginning of main'
'D/GCM     ( 3040): Message class com.google.f.a.a.i'
'--------- beginning of system'
'I/ActivityManager(  502): START u0 {cmp=info.rynkowski.hamsterclient/.presentation.view.activity.FactsListActivity} from uid 10082 on display 0'
'W/AudioTrack(  502): AUDIO_OUTPUT_FLAG_FAST denied by client'
'V/WindowManager(  502): addAppToken: AppWindowToken{2f576ae1 token=Token{13aa5c48 ActivityRecord{16c26eb u0 info.rynkowski.hamsterclient/.presentation.view.activity.FactsListActivity t158}}} to stack=1 task=158 at 1'
'V/WindowManager(  502): Adding window Window{396446c7 u0 info.rynkowski.hamsterclient/info.rynkowski.hamsterclient.presentation.view.activity.FactsListActivity} at 4 of 9 (after Window{185c00a3 u0 info.rynkowski.hamsterclient/info.rynkowski.hamsterclient.presentation.view.activity.MainActivity})'
'W/EGL_emulation(25482): eglSurfaceAttrib not implemented'
'W/OpenGLRenderer(25482): Failed to set EGL_SWAP_BEHAVIOR on surface 0xa28ed240, error=EGL_SUCCESS'
'I/ActivityManager(  502): Displayed info.rynkowski.hamsterclient/.presentation.view.activity.FactsListActivity: +226ms'
"W/SurfaceFlinger(  309): couldn't log to binary event log: overflow."
'W/AudioTrack(  502): AUDIO_OUTPUT_FLAG_FAST denied by client'
'W/EGL_emulation(25482): eglSurfaceAttrib not implemented'
'W/OpenGLRenderer(25482): Failed to set EGL_SWAP_BEHAVIOR on surface 0xa28ed660, error=EGL_SUCCESS'
'I/ActivityManager(  502): START u0 {cmp=info.rynkowski.hamsterclient/.presentation.view.activity.FactFormActivity} from uid 10082 on display 0'
'V/WindowManager(  502): addAppToken: AppWindowToken{2ed16778 token=Token{4c8a0db ActivityRecord{238b25ea u0 info.rynkowski.hamsterclient/.presentation.view.activity.FactFormActivity t158}}} to stack=1 task=158 at 1'
'W/AudioTrack(  502): AUDIO_OUTPUT_FLAG_FAST denied by client'
'I/FactForm(25482): onCreateView()'
'V/WindowManager(  502): Adding window Window{29edb6b6 u0 info.rynkowski.hamsterclient/info.rynkowski.hamsterclient.presentation.view.activity.FactFormActivity} at 4 of 9 (after Window{185c00a3 u0 info.rynkowski.hamsterclient/info.rynkowski.hamsterclient.presentation.view.activity.MainActivity})'
'W/EGL_emulation(25482): eglSurfaceAttrib not implemented'
'W/OpenGLRenderer(25482): Failed to set EGL_SWAP_BEHAVIOR on surface 0xa28edd40, error=EGL_SUCCESS'
'I/ActivityManager(  502): Displayed info.rynkowski.hamsterclient/.presentation.view.activity.FactFormActivity: +246ms'
"W/SurfaceFlinger(  309): couldn't log to binary event log: overflow."
'W/AudioTrack(  502): AUDIO_OUTPUT_FLAG_FAST denied by client'
'W/EGL_emulation(25482): eglSurfaceAttrib not implemented'
'W/OpenGLRenderer(25482): Failed to set EGL_SWAP_BEHAVIOR on surface 0xa28ed820, error=EGL_SUCCESS'
"W/SurfaceFlinger(  309): couldn't log to binary event log: overflow."
^C'USER     PID   PPID  VSIZE  RSS     WCHAN    PC        NAME'
'root      1     0     13224  580   c02115b6 0806c200 S /init'
'--------- beginning of main'
'D/GCM     ( 3040): Message class com.google.f.a.a.i'
'--------- beginning of system'
'I/ActivityManager(  502): START u0 {cmp=info.rynkowski.hamsterclient/.presentation.view.activity.FactsListActivity} from uid 10082 on display 0'
'W/AudioTrack(  502): AUDIO_OUTPUT_FLAG_FAST denied by client'
'V/WindowManager(  502): addAppToken: AppWindowToken{2f576ae1 token=Token{13aa5c48 ActivityRecord{16c26eb u0 info.rynkowski.hamsterclient/.presentation.view.activity.FactsListActivity t158}}} to stack=1 task=158 at 1'
'V/WindowManager(  502): Adding window Window{396446c7 u0 info.rynkowski.hamsterclient/info.rynkowski.hamsterclient.presentation.view.activity.FactsListActivity} at 4 of 9 (after Window{185c00a3 u0 info.rynkowski.hamsterclient/info.rynkowski.hamsterclient.presentation.view.activity.MainActivity})'
'W/EGL_emulation(25482): eglSurfaceAttrib not implemented'
'W/OpenGLRenderer(25482): Failed to set EGL_SWAP_BEHAVIOR on surface 0xa28ed240, error=EGL_SUCCESS'
'I/ActivityManager(  502): Displayed info.rynkowski.hamsterclient/.presentation.view.activity.FactsListActivity: +226ms'
"W/SurfaceFlinger(  309): couldn't log to binary event log: overflow."
'W/AudioTrack(  502): AUDIO_OUTPUT_FLAG_FAST denied by client'
'W/EGL_emulation(25482): eglSurfaceAttrib not implemented'
'W/OpenGLRenderer(25482): Failed to set EGL_SWAP_BEHAVIOR on surface 0xa28ed660, error=EGL_SUCCESS'
'I/ActivityManager(  502): START u0 {cmp=info.rynkowski.hamsterclient/.presentation.view.activity.FactFormActivity} from uid 10082 on display 0'
'V/WindowManager(  502): addAppToken: AppWindowToken{2ed16778 token=Token{4c8a0db ActivityRecord{238b25ea u0 info.rynkowski.hamsterclient/.presentation.view.activity.FactFormActivity t158}}} to stack=1 task=158 at 1'
'W/AudioTrack(  502): AUDIO_OUTPUT_FLAG_FAST denied by client'
'I/FactForm(25482): onCreateView()'
'V/WindowManager(  502): Adding window Window{29edb6b6 u0 info.rynkowski.hamsterclient/info.rynkowski.hamsterclient.presentation.view.activity.FactFormActivity} at 4 of 9 (after Window{185c00a3 u0 info.rynkowski.hamsterclient/info.rynkowski.hamsterclient.presentation.view.activity.MainActivity})'
'W/EGL_emulation(25482): eglSurfaceAttrib not implemented'
'W/OpenGLRenderer(25482): Failed to set EGL_SWAP_BEHAVIOR on surface 0xa28edd40, error=EGL_SUCCESS'
'I/ActivityManager(  502): Displayed info.rynkowski.hamsterclient/.presentation.view.activity.FactFormActivity: +246ms'
"W/SurfaceFlinger(  309): couldn't log to binary event log: overflow."
'W/AudioTrack(  502): AUDIO_OUTPUT_FLAG_FAST denied by client'
'W/EGL_emulation(25482): eglSurfaceAttrib not implemented'
'W/OpenGLRenderer(25482): Failed to set EGL_SWAP_BEHAVIOR on surface 0xa28ed820, error=EGL_SUCCESS'
"W/SurfaceFlinger(  309): couldn't log to binary event log: overflow."
^C% 
```

**Comment by rynkowsg** [comment]
At first pidcat worked for me only on Python 2.

Last two commands that I use on pidcat before it stopped to produce logs.
```
./pidcat.py --color-gc --always-display-tags -i EGL_emulation -i OpenGLRenderer -i libEGL --clean <my-app-id> # bad command --clean
./pidcat.py --color-gc --always-display-tags -i EGL_emulation -i OpenGLRenderer -i libEGL --clear <my-app-id>
```

**Comment by scorpiodawg** [comment]
Happens for me on Ubuntu 16.04 LTS as well, no output from pidcat. Adding the `print repr(...)` does print the lines.

**Comment by glamvian** [comment]
Traceback (most recent call last):
  File "/usr/bin/pidcat", line 192, in <module>
    adb = subprocess.Popen(adb_command, stdin=PIPE, stdout=PIPE, stderr=PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
this error for my linuxmint 18.1 . pidcat can't working
